import {ArrowUpRight, Mail, Sparkles, BrainCircuit, Database} from "lucide-react";

const skills=["Python","SQL","Java","C","Machine Learning","Deep Learning","TensorFlow","Scikit-learn","Pandas","NumPy","Power BI","GitHub","Flask","Data Visualization"];
const projects=[
 {n:"01",title:"SheSecure",tag:"AI • Safety • Mobility",desc:"A safety-focused platform designed to predict safer transportation modes and support real-time route deviation alerts, SOS escalation, and location sharing.",tech:["Python","Machine Learning","Data Analysis"],featured:true},
 {n:"02",title:"Data & ML Projects",tag:"Machine Learning",desc:"Hands-on work across supervised and unsupervised learning, feature engineering, dimensionality reduction, classification and predictive analytics.",tech:["Scikit-learn","Pandas","NumPy"]},
 {n:"03",title:"Power BI Analytics",tag:"Data Visualization",desc:"Interactive dashboards built to transform raw datasets into decision-ready visual insights using Power BI, data modeling and measures.",tech:["Power BI","DAX","EDA"]}
];

export default function Home(){return <main>
<header className="fixed top-0 z-50 w-full border-b border-white/10 bg-[#07070a]/75 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><a href="#home" className="font-semibold tracking-tight">RP<span className="text-violet-400">.</span></a><nav className="hidden gap-7 text-sm text-zinc-400 md:flex">{[["About","about"],["Projects","projects"],["Experience","experience"],["Contact","contact"]].map(([x,id])=><a key={id} className="transition hover:text-white" href={'#'+id}>{x}</a>)}</nav><a href="mailto:r.pandeyji12@gmail.com" className="rounded-full border border-white/15 px-4 py-2 text-xs text-zinc-200 transition hover:bg-white/10">Let's talk</a></div></header>
<section id="home" className="grid-bg relative flex min-h-screen items-center overflow-hidden"><div className="absolute left-1/2 top-1/2 h-96 w-96 -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet-600/15 blur-3xl"/><div className="relative mx-auto w-full max-w-6xl px-6 pt-28"><div className="mb-7 flex items-center gap-3 text-sm font-medium text-violet-300"><span className="h-px w-10 bg-violet-400"/>AI & MACHINE LEARNING STUDENT</div><h1 className="max-w-4xl text-6xl font-semibold tracking-[-.055em] sm:text-7xl md:text-8xl">Building intelligent<br/><span className="bg-gradient-to-r from-white via-zinc-300 to-violet-400 bg-clip-text text-transparent">systems for real life.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-zinc-400">I'm Rajat Pandey, a B.Tech AI & ML student at SIT Pune exploring Machine Learning, Generative AI and Agentic AI — and turning ideas into useful products.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#projects" className="flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-black transition hover:scale-[1.02]">View projects <ArrowUpRight size={16}/></a><a href="mailto:r.pandeyji12@gmail.com" className="flex items-center gap-2 rounded-full border border-white/15 px-6 py-3 text-sm text-white transition hover:bg-white/10"><Mail size={16}/> Contact me</a></div><div className="mt-20 grid max-w-3xl grid-cols-1 gap-3 sm:grid-cols-3"><Stat icon={<BrainCircuit size={18}/>} t="AI / ML" s="Core focus"/><Stat icon={<Sparkles size={18}/>} t="GenAI" s="Exploring"/><Stat icon={<Database size={18}/>} t="Data" s="Build & analyze"/></div></div></section>
<section id="about" className="mx-auto max-w-6xl px-6 py-28"><SectionTitle eyebrow="ABOUT" title="Curious about intelligence. Serious about impact."/><div className="grid gap-10 md:grid-cols-[1.2fr_.8fr]"><p className="text-xl leading-9 text-zinc-300">I'm currently pursuing a B.Tech in Artificial Intelligence & Machine Learning at Symbiosis Institute of Technology, Pune. My interests sit at the intersection of AI, data and real-world problem solving. I enjoy taking an idea from a problem statement to a working prototype.</p><div className="rounded-3xl border border-white/10 bg-white/[.035] p-7"><div className="text-sm text-zinc-500">EDUCATION</div><div className="mt-4 text-lg font-semibold">Symbiosis Institute of Technology</div><div className="mt-1 text-zinc-400">B.Tech — Artificial Intelligence & Machine Learning</div><div className="mt-5 text-sm text-zinc-500">2024 — 2028</div></div></div></section>
<section id="projects" className="border-y border-white/10 bg-white/[.018] py-28"><div className="mx-auto max-w-6xl px-6"><SectionTitle eyebrow="SELECTED WORK" title="Projects that solve actual problems."/><div className="grid gap-5 md:grid-cols-3">{projects.map(p=><article key={p.n} className={'group flex min-h-[390px] flex-col rounded-3xl border p-7 transition duration-300 hover:-translate-y-1 '+(p.featured?'border-violet-400/30 bg-violet-500/[.07] glow':'border-white/10 bg-white/[.035]')}><div className="flex justify-between text-xs text-zinc-500"><span>{p.n}</span>{p.featured&&<span className="text-violet-300">FEATURED</span>}</div><div className="mt-16"><div className="text-xs uppercase tracking-[.18em] text-zinc-500">{p.tag}</div><h3 className="mt-3 text-3xl font-semibold tracking-tight">{p.title}</h3><p className="mt-4 leading-7 text-zinc-400">{p.desc}</p></div><div className="mt-auto flex flex-wrap gap-2 pt-8">{p.tech.map(t=><span key={t} className="rounded-full border border-white/10 px-3 py-1 text-xs text-zinc-400">{t}</span>)}</div></article>)}</div></div></section>
<section id="experience" className="mx-auto max-w-6xl px-6 py-28"><SectionTitle eyebrow="EXPERIENCE & LEADERSHIP" title="Learning by building and leading."/><div className="divide-y divide-white/10 rounded-3xl border border-white/10 bg-white/[.025]">{[["2026 — Present","MED-TECH Friday Club","Vertical Lead — Intelligent Clinical Decision Support"],["2026 — Present","Symbiosis Economic Club","Core Team"],["2026","Symbitech","Organizing Team"]].map(x=><div key={x[1]} className="grid gap-3 p-7 md:grid-cols-[150px_1fr_1.4fr] md:items-center"><div className="text-sm text-zinc-500">{x[0]}</div><div className="font-semibold">{x[1]}</div><div className="text-zinc-400">{x[2]}</div></div>)}</div></section>
<section className="border-y border-white/10 py-24"><div className="mx-auto max-w-6xl px-6"><SectionTitle eyebrow="TOOLKIT" title="Technologies I work with."/><div className="flex flex-wrap gap-3">{skills.map(s=><span key={s} className="rounded-full border border-white/10 bg-white/[.035] px-5 py-3 text-sm text-zinc-300 transition hover:border-violet-400/40 hover:text-white">{s}</span>)}</div></div></section>
<section id="contact" className="mx-auto max-w-6xl px-6 py-32"><div className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-violet-500/10 via-white/[.03] to-transparent p-8 text-center sm:p-16"><div className="mx-auto max-w-3xl"><div className="text-sm tracking-[.2em] text-violet-300">LET'S CONNECT</div><h2 className="mt-5 text-5xl font-semibold tracking-[-.04em] sm:text-6xl">Have an idea?<br/>Let's build it.</h2><p className="mx-auto mt-6 max-w-xl leading-7 text-zinc-400">Open to conversations around AI, ML, projects, collaborations and opportunities.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href="mailto:r.pandeyji12@gmail.com" className="flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-black"><Mail size={16}/> Email me</a></div></div></div></section>
<footer className="border-t border-white/10"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-6 py-8 text-sm text-zinc-500 sm:flex-row sm:items-center sm:justify-between"><div>© 2026 Rajat Pandey</div><div className="flex gap-5"><a href="mailto:r.pandeyji12@gmail.com" className="hover:text-white"><Mail size={18}/></a><a href="https://github.com/Rajatpandey02" target="_blank" rel="noreferrer" aria-label="GitHub" className="hover:text-white"><span className="text-xs font-semibold">GH</span></a><a href="https://www.linkedin.com/in/rajat-pandey-933b87321/" target="_blank" rel="noreferrer" aria-label="LinkedIn" className="hover:text-white"><span className="text-sm font-semibold leading-none">in</span></a></div></div></footer>
</main>}
function SectionTitle({eyebrow,title}:{eyebrow:string,title:string}){return <div className="mb-14"><div className="text-xs font-medium tracking-[.2em] text-violet-300">{eyebrow}</div><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.035em] sm:text-5xl">{title}</h2></div>}
function Stat({icon,t,s}:{icon:React.ReactNode,t:string,s:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><div className="text-violet-300">{icon}</div><div className="mt-4 font-semibold">{t}</div><div className="mt-1 text-sm text-zinc-500">{s}</div></div>}